version: '3' # 파일 규격 버전으로 “3”이라만 적으면 3으로 시작하는 최신 버전을 사용한다는 의미

services:

  redis-sentinel1:
    image: lgatica/redis-sentinel:4.0.2
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26379
      - MASTERHOST=172.31.31.38
      - CLIENTHOST=172.31.31.38
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
    volumes:
      - "../../sentinel-data/sentinel1:/redis"
    restart: always

  redis-sentinel2:
    image: lgatica/redis-sentinel:4.0.2
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26380
      - MASTERHOST=172.31.31.38
      - CLIENTHOST=172.31.31.38
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
    volumes:
      - "../../sentinel-data/sentinel2:/redis"
    restart: always

  redis-sentinel3:
    image: lgatica/redis-sentinel:4.0.2
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26381
      - MASTERHOST=172.31.31.38
      - CLIENTHOST=172.31.31.38
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
    volumes:
      - "../../sentinel-data/sentinel3:/redis"
    restart: always