version: '3' # 파일 규격 버전으로 “3”이라만 적으면 3으로 시작하는 최신 버전을 사용한다는 의미
services:

  redis1:
    image: yim0823/redis-cluster
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6379
      - MASTERPORT=
      - CLIENTHOST=172.31.31.38
      - MASTERHOST=
    restart: always

  redis2:
    image: yim0823/redis-cluster
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6380
      - MASTERPORT=6379
      - CLIENTHOST=172.31.31.38
      - MASTERHOST=172.31.31.38
    restart: always

  redis3:
    image: yim0823/redis-cluster
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6381
      - MASTERPORT=6379
      - CLIENTHOST=172.31.31.38
      - MASTERHOST=172.31.31.38
    restart: always