version: '3' # 파일 규격 버전으로 “3”이라만 적으면 3으로 시작하는 최신 버전을 사용한다는 의미
services:

  redis1:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6379
      - MASTERPORT=
      - CLIENTHOST=172.31.31.38
      - MASTERHOST=
    volumes:
      - "../../redis-data/redis1:/data"
    restart: always

  redis2:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6380
      - MASTERPORT=6379
      - CLIENTHOST=172.31.31.38
      - MASTERHOST=172.31.31.38
    volumes:
      - "../../redis-data/redis2:/data"
    restart: always

  redis3:
    image: redis:5.0-alpine
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6381
      - MASTERPORT=6379
      - CLIENTHOST=172.31.31.38
      - MASTERHOST=172.31.31.38
    volumes:
      - "../../redis-data/redis3:/data"
    restart: always