apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redis3
  name: redis3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis3
    spec:
      containers:
        - env:
            - name: CLIENTHOST
              value: 172.31.31.38
            - name: CLIENTPORT
              value: "6381"
            - name: MASTERHOST
              value: 172.31.31.38
            - name: MASTERPORT
              value: "6379"
            - name: REQUIREPASS
              value: password1234
          image: yim0823/redis-cluster
          name: redis3
          volumeMounts:
            - name: data
              mountPath: /home/redis/redis-data/redis1
          resources: {}
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
status: {}