apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis-sentinel
    redis-sentinel: "true"
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sentinel
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: redis-sentinel
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - mountPath: /redis-data
          name: data
      - name: sentinel
        image: k8s.gcr.io/redis:v1
        env:
        - name: SENTINEL
          value: "true"
        ports:
        - containerPort: 26379
      volumes:
      - name: data
        emptyDir: {}