apiVersion: v1
kind: Service
metadata:
  name: redis-slave03
  labels:
    app: redis-sentinel
    role: slave
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-sentinel
    role: slave
    tier: backend