apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-01
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0b48c6152e38c6c98