apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis
        image: k8s.gcr.io/redis:v1
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 1Gi
            memory: 4Gi
          limits:
            cpu: 2Gi
            memory: 5Gi
        volumeMounts:
        - mountPath: /redis-data
          name: data
      volumes:
        - name: data