rootUser:
  password: root
  forcePassword: true

db:
  user: dcos
  password: dnjfkqpf!1
  name: dcos
  forcePassword: true

replication:
  password: dnjfkqpf!1

master:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 4Gi

slave:
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 4Gi

metrics:
  enabled: false