## Cluster settings
cluster:
  enabled: true
  slaveCount: 3

## Use password authentication
usePassword: false

##
## Redis Master parameters
##
master:
  persistence:
    enabled: false

  statefulset:
    updateStrategy: RollingUpdate

##
## Redis Slave properties
##
slave:
  persistence:
    enabled: false

  statefulset:
    updateStrategy: RollingUpdate
