apiVersion: v1
kind: Service
metadata:
  name: redis-haproxy
  labels:
    app: redis-ha
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #  type: LoadBalancer
  ports:
  - name: redis-master
    protocol: TCP
    port: 5000
    nodePort: 31001
  - name: redis-slave
    protocol: TCP
    port: 5001
    nodePort: 31002
  - name: stats
    protocol: TCP
    port: 9000
    nodePort: 31003
  selector:
    app: redis-haproxy