apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-haproxy
  labels:
    app: redis-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-haproxy
  template:
    metadata:
      labels:
        app: redis-haproxy
    spec:
      containers:
      - name: haproxy
        image: yim0823/redis-haproxy
        ports:
        - containerPort: 5000
          name: redis-master
        - containerPort: 5001
          name: redis-slave
        - containerPort: 9000
          name: stats
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 2
          failureThreshold: 2
          tcpSocket:
            port: 9000
